# cloudbuild.yaml
steps:
  - name: 'docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/app', '.']

serviceAccount: projects/$PROJECT_ID/serviceAccounts/my-build-sa@${PROJECT_ID}.iam.gserviceaccount.com

# choose ONE of the following blocks ↓↓↓

# (A) Send logs to your own bucket
logsBucket: gs://my-build-logs          # bucket must already exist and be writable by the SA

# --- OR ---

# (B) Let Cloud Build create a regional bucket automatically
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

# --- OR ---

# (C) Use Cloud Logging only
options:
  logging: CLOUD_LOGGING_ONLY           # or NONE
